#ifndef ORIENTATIONMAP_GLOBAL_H
#define ORIENTATIONMAP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ORIENTATIONMAP_LIBRARY)
#  define ORIENTATIONMAP_EXPORT Q_DECL_EXPORT
#else
#  define ORIENTATIONMAP_EXPORT Q_DECL_IMPORT
#endif

#endif // ORIENTATIONMAP_GLOBAL_H
